
package org.opcfoundation.webservices.xmlda._1;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Service", targetNamespace = "http://opcfoundation.org/webservices/XMLDA/1.0/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Service {


    /**
     * 
     * @param parameters
     * @return
     *     returns org.opcfoundation.webservices.xmlda._1.GetStatusResponse
     */
    @WebMethod(operationName = "GetStatus", action = "http://opcfoundation.org/webservices/XMLDA/1.0/GetStatus")
    @WebResult(name = "GetStatusResponse", targetNamespace = "http://opcfoundation.org/webservices/XMLDA/1.0/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetStatusResponse getStatus(
        @WebParam(name = "GetStatus", targetNamespace = "http://opcfoundation.org/webservices/XMLDA/1.0/", partName = "parameters")
        GetStatus parameters);

    /**
     * 
     * @param errors
     * @param itemList
     * @param rItemList
     * @param readResult
     * @param options
     */
    @WebMethod(operationName = "Read", action = "http://opcfoundation.org/webservices/XMLDA/1.0/Read")
    @RequestWrapper(localName = "Read", targetNamespace = "http://opcfoundation.org/webservices/XMLDA/1.0/", className = "org.opcfoundation.webservices.xmlda._1.Read")
    @ResponseWrapper(localName = "ReadResponse", targetNamespace = "http://opcfoundation.org/webservices/XMLDA/1.0/", className = "org.opcfoundation.webservices.xmlda._1.ReadResponse")
    public void read(
        @WebParam(name = "Options", targetNamespace = "http://opcfoundation.org/webservices/XMLDA/1.0/")
        RequestOptions options,
        @WebParam(name = "ItemList", targetNamespace = "http://opcfoundation.org/webservices/XMLDA/1.0/")
        ReadRequestItemList itemList,
        @WebParam(name = "ReadResult", targetNamespace = "http://opcfoundation.org/webservices/XMLDA/1.0/", mode = WebParam.Mode.OUT)
        Holder<ReplyBase> readResult,
        @WebParam(name = "RItemList", targetNamespace = "http://opcfoundation.org/webservices/XMLDA/1.0/", mode = WebParam.Mode.OUT)
        Holder<ReplyItemList> rItemList,
        @WebParam(name = "Errors", targetNamespace = "http://opcfoundation.org/webservices/XMLDA/1.0/", mode = WebParam.Mode.OUT)
        Holder<List<OPCError>> errors);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.opcfoundation.webservices.xmlda._1.WriteResponse
     */
    @WebMethod(operationName = "Write", action = "http://opcfoundation.org/webservices/XMLDA/1.0/Write")
    @WebResult(name = "WriteResponse", targetNamespace = "http://opcfoundation.org/webservices/XMLDA/1.0/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public WriteResponse write(
        @WebParam(name = "Write", targetNamespace = "http://opcfoundation.org/webservices/XMLDA/1.0/", partName = "parameters")
        Write parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.opcfoundation.webservices.xmlda._1.SubscribeResponse
     */
    @WebMethod(operationName = "Subscribe", action = "http://opcfoundation.org/webservices/XMLDA/1.0/Subscribe")
    @WebResult(name = "SubscribeResponse", targetNamespace = "http://opcfoundation.org/webservices/XMLDA/1.0/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public SubscribeResponse subscribe(
        @WebParam(name = "Subscribe", targetNamespace = "http://opcfoundation.org/webservices/XMLDA/1.0/", partName = "parameters")
        Subscribe parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.opcfoundation.webservices.xmlda._1.SubscriptionPolledRefreshResponse
     */
    @WebMethod(operationName = "SubscriptionPolledRefresh", action = "http://opcfoundation.org/webservices/XMLDA/1.0/SubscriptionPolledRefresh")
    @WebResult(name = "SubscriptionPolledRefreshResponse", targetNamespace = "http://opcfoundation.org/webservices/XMLDA/1.0/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public SubscriptionPolledRefreshResponse subscriptionPolledRefresh(
        @WebParam(name = "SubscriptionPolledRefresh", targetNamespace = "http://opcfoundation.org/webservices/XMLDA/1.0/", partName = "parameters")
        SubscriptionPolledRefresh parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.opcfoundation.webservices.xmlda._1.SubscriptionCancelResponse
     */
    @WebMethod(operationName = "SubscriptionCancel", action = "http://opcfoundation.org/webservices/XMLDA/1.0/SubscriptionCancel")
    @WebResult(name = "SubscriptionCancelResponse", targetNamespace = "http://opcfoundation.org/webservices/XMLDA/1.0/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public SubscriptionCancelResponse subscriptionCancel(
        @WebParam(name = "SubscriptionCancel", targetNamespace = "http://opcfoundation.org/webservices/XMLDA/1.0/", partName = "parameters")
        SubscriptionCancel parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.opcfoundation.webservices.xmlda._1.BrowseResponse
     */
    @WebMethod(operationName = "Browse", action = "http://opcfoundation.org/webservices/XMLDA/1.0/Browse")
    @WebResult(name = "BrowseResponse", targetNamespace = "http://opcfoundation.org/webservices/XMLDA/1.0/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public BrowseResponse browse(
        @WebParam(name = "Browse", targetNamespace = "http://opcfoundation.org/webservices/XMLDA/1.0/", partName = "parameters")
        Browse parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.opcfoundation.webservices.xmlda._1.GetPropertiesResponse
     */
    @WebMethod(operationName = "GetProperties", action = "http://opcfoundation.org/webservices/XMLDA/1.0/GetProperties")
    @WebResult(name = "GetPropertiesResponse", targetNamespace = "http://opcfoundation.org/webservices/XMLDA/1.0/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetPropertiesResponse getProperties(
        @WebParam(name = "GetProperties", targetNamespace = "http://opcfoundation.org/webservices/XMLDA/1.0/", partName = "parameters")
        GetProperties parameters);

}
