
package org.opcfoundation.webservices.xmlda._1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Service", targetNamespace = "http://opcfoundation.org/webservices/XMLDA/1.0/", wsdlLocation = "file:/home/jens/Development/workspace_os13/org.openscada.opc.xmlda/input/my.wsdl")
public class Service_Service
    extends javax.xml.ws.Service
{

    private final static URL SERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICE_EXCEPTION;
    private final static QName SERVICE_QNAME = new QName("http://opcfoundation.org/webservices/XMLDA/1.0/", "Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/jens/Development/workspace_os13/org.openscada.opc.xmlda/input/my.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICE_WSDL_LOCATION = url;
        SERVICE_EXCEPTION = e;
    }

    public Service_Service() {
        super(__getWsdlLocation(), SERVICE_QNAME);
    }

    public Service_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICE_QNAME, features);
    }

    public Service_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE_QNAME);
    }

    public Service_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE_QNAME, features);
    }

    public Service_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Service_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Service
     */
    @WebEndpoint(name = "ServiceSoap")
    public org.opcfoundation.webservices.xmlda._1.Service getServiceSoap() {
        return super.getPort(new QName("http://opcfoundation.org/webservices/XMLDA/1.0/", "ServiceSoap"), Service.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Service
     */
    @WebEndpoint(name = "ServiceSoap")
    public org.opcfoundation.webservices.xmlda._1.Service getServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://opcfoundation.org/webservices/XMLDA/1.0/", "ServiceSoap"), Service.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICE_EXCEPTION!= null) {
            throw SERVICE_EXCEPTION;
        }
        return SERVICE_WSDL_LOCATION;
    }

}
